import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useRef,
  useState,
  type ReactNode,
} from 'react';
import { useApi } from './api/hooks';

/**
 * LLM-backed localization. Any string passed through `t()` becomes
 * translatable into any supported locale via ARAG; results are cached in
 * localStorage (client) and the DB (server) so each (string, locale) pair is
 * generated by the model at most once, ever.
 */
export const LOCALES: Record<string, string> = {
  en: 'English',
  es: 'Español',
  pt: 'Português',
  fr: 'Français',
  de: 'Deutsch',
  it: 'Italiano',
  nl: 'Nederlands',
  ja: '日本語',
  zh: '中文 (简体)',
};
export type Locale = keyof typeof LOCALES;

interface I18nCtx {
  locale: Locale;
  setLocale: (l: Locale) => void;
  t: (source: string) => string;
  translating: boolean;
}

const Ctx = createContext<I18nCtx | null>(null);
const LKEY = 'pf.portal.locale';
const cacheKey = (l: string): string => `pf.portal.i18n.${l}`;

function loadCache(locale: string): Record<string, string> {
  try {
    return JSON.parse(localStorage.getItem(cacheKey(locale)) ?? '{}') as Record<string, string>;
  } catch {
    return {};
  }
}

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(() => {
    const s = localStorage.getItem(LKEY) as Locale | null;
    return s && s in LOCALES ? s : 'en';
  });
  const [dict, setDict] = useState<Record<string, string>>(() => loadCache(locale));
  const [translating, setTranslating] = useState(false);
  const seen = useRef<Set<string>>(new Set());
  const dictRef = useRef(dict);
  dictRef.current = dict;

  const translate = useApi.i18n.translate();

  const setLocale = useCallback((l: Locale) => {
    localStorage.setItem(LKEY, l);
    setLocaleState(l);
    setDict(loadCache(l));
  }, []);

  const t = useCallback(
    (source: string): string => {
      if (locale === 'en') return source;
      seen.current.add(source);
      return dictRef.current[source] ?? source;
    },
    [locale],
  );

  // Flush newly-seen, untranslated strings to the server in batches.
  useEffect(() => {
    if (locale === 'en') return;
    let cancelled = false;
    const tick = async () => {
      const missing = [...seen.current].filter((s) => !(s in dictRef.current));
      if (missing.length === 0) return;
      setTranslating(true);
      try {
        const res = await translate.mutateAsync({ locale, texts: missing.slice(0, 200) });
        if (cancelled) return;
        setDict((prev) => {
          const next = { ...prev, ...res };
          localStorage.setItem(cacheKey(locale), JSON.stringify(next));
          return next;
        });
      } catch {
        /* keep English fallback */
      } finally {
        if (!cancelled) setTranslating(false);
      }
    };
    const iv = setInterval(tick, 700);
    void tick();
    return () => {
      cancelled = true;
      clearInterval(iv);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [locale]);

  return (
    <Ctx.Provider value={{ locale, setLocale, t, translating }}>{children}</Ctx.Provider>
  );
}

export function useI18n(): I18nCtx {
  const c = useContext(Ctx);
  if (!c) throw new Error('useI18n outside I18nProvider');
  return c;
}
